export { default as HomeScreen } from './Home'
export { default as MyPageScreen } from './MyPage'
export { default as ChatModal } from './ChatModal'
export { default as SplashScreen } from './Splash'
export { default as LoginScreen } from './Login'
export { default as RegisterScreen } from './Register'
export { BasicQuestionnaire } from './basicQuestionnaireModal'
export { default as Diagnosis } from './Diagnosis'
export { default as ChatDiagnosis } from './ChatDiagnosis'
console.disableYellowBox = true
